  version: '3'
  services:
    osf_scraper_api:
      image: '${BUILD_ENV}_osf_scraper_api'
      build:
        context: .
        args:
          - BUILD_ENV
      ports:
        - '80:80'
        - '443:443'
      links:
        - redis
        - selenium
    redis:
      image: redis
      ports:
        - "6379"
    selenium:
      image: selenium/standalone-firefox
      ports:
        - "4444:4444"

