  version: '3'
  services:
    prod:
      image: '${BUILD_ENV}_osf_scraper_api'
      build:
        context: .
        args:
          - BUILD_ENV
      ports:
        - '80:80'
        - '443:443'
      links:
        - redis
    redis:
      image: redis
      ports:
        - "6379"

