  version: '3'
  services:
    prod:
      image: prod_osf_scraper_api
      build:
        context: .
        args:
          - BUILD_ENV=prod
      ports:
        - '80:80'
        - '443:443'
    redis:
      image: redis
      ports:
        - "6379"
    staging:
      image: staging_osf_scraper_api
      build:
        context: .
        args:
          - BUILD_ENV=staging
      ports:
        - '80:80'
        - '443:443'

