
- name: Log into DockerHub
  docker_login:
    username: "{{docker_username}}"
    password: "{{docker_password}}"

- name: Ensure docker-compose file is up to date
  template:
  src: ../docker-compose.yml
  dest: "/containers/docker-compose/my-cool-web/docker-compose.yml"

- name: Run docker-compose up
  command: /usr/local/bin/docker-compose -f /containers/docker-compose/my-cool-web/docker-compose.yml up -d

