---

- hosts: staging-servers
  user: ubuntu
  sudo: True
  roles:
    - role: angstwad.docker_ubuntu
      docker_group_members: ['ubuntu']
      pip_version_docker_py: '1.10.6'
      pip_version_docker_compose: '1.9.0'
      tags: ['docker']

  tasks:

    - name: install common packages
      action: apt pkg=$item state=installed
      with_items:
        - python-dev
        - python-setuptools
        - git-core

    - name: install pip
      action: easy_install name=pip

    - name: install virtualenv and uwsgi
      action: pip name={{item.name}} version={{item.version}}
      with_items:
        - { name: 'virtualenv', version: '14.0.6' }

    - name: install docker python integration
      action: pip name={{item.name}} version={{item.version}}
      with_items:
        - { name: 'docker', version: '2.4.2' }
        - { name: 'docker-compose', version: '1.14.0' }

